# Generated by Django 2.1.5 on 2023-07-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('sign_in', models.DateTimeField(default=None, verbose_name='Sign In')),
                ('sign_out', models.DateTimeField(default=None, verbose_name='Sign In')),
                ('employee', models.CharField(default=None, max_length=20, verbose_name='Employe')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
        ),
    ]
