# Generated by Django 2.1.5 on 2023-07-22 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_tags', '0001_initial'),
        ('hr_departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('salary', models.CharField(default=None, max_length=20, verbose_name='Expected Salary')),
                ('ot_rate', models.CharField(default=None, max_length=20, verbose_name='OT Rate')),
                ('allowance', models.CharField(default=None, max_length=20, verbose_name='Allowance')),
                ('overtime', models.CharField(default=None, max_length=20, verbose_name='Overtime')),
                ('deduction', models.CharField(default=None, max_length=10, verbose_name='Deduction')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='', verbose_name='Image')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_departments.DepartmentModel')),
                ('tags', models.ManyToManyField(to='hr_tags.PayrollTagModel')),
            ],
        ),
    ]
