# Generated by Django 2.1.5 on 2023-07-22 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('meeting_date', models.DateField(default=django.utils.timezone.now, verbose_name='Meeting Date')),
                ('total_employees', models.CharField(default=None, max_length=20, verbose_name='Total Employees')),
                ('note', models.TextField(max_length=100, verbose_name='Note')),
                ('status', models.CharField(default='draft', max_length=10, verbose_name='Status')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('create_date', models.DateField(default=django.utils.timezone.now, verbose_name='Create Date')),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='', verbose_name='Attachment')),
            ],
        ),
    ]
