"""
Django settings for HRMS project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@=v@ww4e4@nhuu#_nbv76!0u70p5yf7qyka0g0e%l91-f_dzc+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hr_employees.apps.HrEmployeesConfig',
    'hr_contracts.apps.HrContractsConfig',
    'hr_jobs.apps.HrJobsConfig',
    'hr_expenses.apps.HrExpensesConfig',
    'hr_attendances.apps.HrAttendancesConfig',
    'hr_departments.apps.HrDepartmentsConfig',
    'hr_payrolls.apps.HrPayrollsConfig',
    'hr_tags.apps.HrTagsConfig',
    'account.apps.AccountConfig',
    'hr_recruitments.apps.HrRecruitmentsConfig'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HRMS.urls'

DATETIME_INPUT_FORMATS = [
    '%Y-%m-%dT%H:%M',# '2022-11-22T04:04'
    '%Y-%m-%d %H:%M:%S',# '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M:%S.%f', # '2006-10-25 14:30:59.000200'
    '%Y-%m-%d %H:%M',# '2006-10-25 14:30'
    '%Y-%m-%d',# '2006-10-25'
    '%m/%d/%Y %H:%M:%S',# '10/25/2006 14:30:59'
    '%m/%d/%Y %H:%M:%S.%f', # '10/25/2006 14:30:59.000200'
    '%m/%d/%Y %H:%M',# '10/25/2006 14:30'
    '%m/%d/%Y',# '10/25/2006'
    '%m/%d/%y %H:%M:%S',# '10/25/06 14:30:59'
    '%m/%d/%y %H:%M:%S.%f', # '10/25/06 14:30:59.000200'
    '%m/%d/%y %H:%M',# '10/25/06 14:30'
    '%m/%d/%y',# '10/25/06'
]

USE_L10N = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HRMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
os.path.join(BASE_DIR,'static')
]
