# Generated by Django 2.1.5 on 2023-07-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_tags', '0001_initial'),
        ('hr_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('quantity', models.IntegerField(default=None, verbose_name='Quantity')),
                ('product', models.CharField(default=None, max_length=20, verbose_name='Product')),
                ('price', models.CharField(default=None, max_length=20, verbose_name='Price')),
                ('total', models.CharField(default=None, max_length=20, verbose_name='Total')),
                ('reason', models.CharField(default='draft', max_length=10, verbose_name='Status')),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='', verbose_name='Image')),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hr_jobs.JobModel')),
                ('tags', models.ManyToManyField(to='hr_tags.ExpenseTagModel')),
            ],
        ),
    ]
