# Generated by Django 2.1.5 on 2023-07-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
